import './globals.css'
import { Inter } from 'next/font/google';
import Authprovider from './components/Authprovider/providers';
import Header from './components/header';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shoppersprey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Authprovider>{children}</Authprovider>
        <Footer/>
      </body>
    </html> 
  );
}
